### ISSUE TITLE
How to verify that this is running?

### ISSUE THREAD

**Issue by naldikt** [ikiapps/Setup-Xcode-Derived-Data-RAM-Disk#2]
Do you have any command we can use to see if the script's actually been run by launchctl?

**Comment by d108** [comment]
To verify that the script has run from using `launchctl` and that the RAM disk is available, you can check the Finder for a volume named `DerivedData`. If you run `mount` from the command line you should also be able to see it. 

Does this solve your issue?

**Comment by naldikt** [comment]
Yeah - I see the folder under Finder and Desktop.  Thanks!
